name: Go

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16
      - uses: actions/checkout@v2
      - name: Test
        run: cd module && go test ./... -mod=readonly -timeout 30m -coverprofile=profile.out -covermode=atomic -race
